auth_base_url = "https://auth-worker-dev.vg-stavenko.workers.dev"
support_base_url = "https://support-worker-dev.vg-stavenko.workers.dev"
payment_base_url = "https://payment-worker-dev.vg-stavenko.workers.dev"
