api_base_url = ""
auth_base_url = "https://auth-worker.vg-stavenko.workers.dev"
push_base_url = "https://main-flow.vg-stavenko.workers.dev"
ai_base_url = "https://ai-worker.vg-stavenko.workers.dev"
payment_base_url = "https://payment-worker.vg-stavenko.workers.dev"
ocr_queue_base_url = "https://ocr-queue.vg-stavenko.workers.dev"
sync_base_url = "https://sync-worker.vg-stavenko.workers.dev"
bug_report_base_url = "https://bug-report-worker.vg-stavenko.workers.dev"
support_base_url = "https://support-worker.vg-stavenko.workers.dev"
